name: VRNcore
version: @version@
main: net.skeagle.vrncore.VRNcore
author: Skeagle
description: "The core plugin for VRN Network, containing many essentials-inspired commands and features, admin tools, cosmetics, and other helpful utilities."
depend: [ VRNLib ]
softdepend: [ Vault, LuckPerms ]
api-version: 1.17