name: VRNcore
version: '${version}'
main: net.skeagle.vrncore.VRNcore
author: Skeagle
description: "A plugin containing many essentials-inspired commands and features, admin tools, cosmetics, and other helpful utilities."
depend: [ VRNLib ]
softdepend: [ Vault, LuckPerms, SuperVanish, PremiumVanish ]
api-version: 1.19