name: VRNcore
version: ${project.version}
main: ${main.class}
api-version: 1.13
commands: 
    vrn:
        description: VRNcore help command.
        usage: /vrn <page>
    clearchat:
        description: Clears all chat.
        usage: /clearchat
    sysinfo:
        description: Displays server platform information.
        usage: /sysinfo
    gamemode:
        aliases: gm
        description: Changes your (or another player's) gamemode.
        usage: /gamemode <gamemode> [player]
    heal:
        description: Heals you.
        usage: /heal <player>
    spawn:
        description: Teleports to server spawn.
        usage: /spawn
    setspawn:
        description: Sets the server spawn.
        usage: /setspawn
    fly:
        description: Toggles flight mode.
        usage: /fly
    vrnversion:
        description: Gets the current VRNcore version.
        usage: /vrnversion
    vanish:
        description: Toggles invisibility.
        usage: /vanish
    rename:
        description: Renames an item in your main hand.
        usage: /rename <name>
    pweather:
        description: Toggles personal weather.
        usage: /pweather <sun:rain>
    ptime:
        description: Toggles personal time.
        usage: /ptime <day:night>
    day:
        description: Sets the time to day.
        usage: /day <all>
    night:
        description: Sets the time to night.
        usage: /night <all>
    rain:
        description: Sets the weather to rain.
        usage: /rain <all>
    sun:
        description: Sets the weather to sun.
        usage: /sun <all>
    slap:
        description: Kill a player.
        usage: /slap <player>
    speed:
        description: Change your fly or walk speed.
        usage: /speed <value:reset>
    god:
        description: Toggle invulnerability.
        usage: /god <player>
    mute:
        description: Toggle a player's ability to chat.
        usage: /mute <player>
    broadcast:
        aliases: bc
        description: Send a message to the whole server.
        usage: /broadcast <message>
    invsee:
        description: Open a player's inventory.
        usage: /invsee <player>
    echest:
        aliases: enderchest
        description: Open a player's enderchest.
        usage: /echest <player>
    smite:
        description: Strike a player with lightning.
        usage: /smite <player:all>
    enchant:
        description: Open a virtual enchantment table.
        usage: /enchant
    craft:
        description: Open a virtual crafting table.
        usage: /craft
    ggive:
        description: A GUI /give manager.
        usage: /ggive
    tphere:
        description: Teleport another player to your location.
        usage: /tphere <player>
    tpall:
        description: Teleport all players to your location.
        usage: /tpall
    ban:
        description: Bans a player.
        usage: /ban <player> <time:reason>
    kick:
        description: Kicks a player.
        usage: /kick <player> <reason>
    nick:
        aliases: nickname
        description: Changes your display name.
        usage: /nick <nickname>